theme: jekyll-theme-minimal
title: THE SUCCESS OF INCLUSIVE CINEMA
description: The Inspiration team final project
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: our_README
    url: our_README
